apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "amandate.cnpgClusterName" . }}
  labels:
    {{- include "amandate.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  instances: {{ .Values.database.cnpg.instances }}
  superuserSecret:
    name: db-admin-secret
  bootstrap:
    initdb:
      database: {{ .Values.database.name | quote }}
      owner: {{ .Values.database.appUser | quote }}
      secret:
        name: application-secret
  storage:
    size: {{ .Values.database.cnpg.storage.size | quote }}
    storageClass: {{ .Values.database.cnpg.storage.storageClass | quote }}
  resources:
    {{- toYaml .Values.database.cnpg.resources | nindent 4 }}
  postgresql:
    parameters:
      {{- toYaml .Values.database.cnpg.parameters | nindent 6 }}
