apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "amandate.configmapName" . }}
  labels:
    {{- include "amandate.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  CHAT_DEEP_LINK_BASE_URL: {{ .Values.config.chatDeepLinkBaseUrl | quote }}
  ENABLE_ADMIN_VIEW: {{ .Values.config.enableAdminView | quote }}
  ADMIN_USER_ID: {{ .Values.config.adminUserId | quote }}
  {{- with .Values.backend.extraEnv }}
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
