apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "amandate.applicationSecretName" . }}
  labels:
    {{- include "amandate.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ .Values.vaultStaticSecret.mount }}
  path: {{ .Values.vaultStaticSecret.applicationSecret.path }}
  refreshAfter: "30s"
  hmacSecretData: true
  vaultAuthRef: {{ .Values.vaultStaticSecret.vaultAuthRef }}
  destination:
    name: {{ include "amandate.applicationSecretName" . }}
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ include "amandate.dbAdminSecretName" . }}
  labels:
    {{- include "amandate.labels" . | nindent 4 }}
spec:
  type: kv-v2
  mount: {{ .Values.vaultStaticSecret.mount }}
  path: {{ .Values.vaultStaticSecret.dbAdminSecret.path }}
  refreshAfter: "30s"
  hmacSecretData: true
  vaultAuthRef: {{ .Values.vaultStaticSecret.vaultAuthRef }}
  destination:
    name: {{ include "amandate.dbAdminSecretName" . }}
    create: true
    overwrite: true
